CREATE TABLE IF NOT EXISTS users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NELL UNIQUE,
    password_hash VARCHAR(255) NOT NELL,
    created_at Timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PRODUCTS (ID
 INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(100) NOT NULL,
	description TEXT, price DECIMAL (10, 2) NOT NULL,
	date_added DAFAULT CURRENT_TIMESTAMP);

CREATE TABLE ORDERS (ID INTEGER PRIMARY KEY AUTOINCREMENT, user_ID INTEGER NOT NULL, 
	product_ID FOREIGN KEY (products), 
    quantity INTEGER NOT NULL,
    total_price DECIMAL (10, 2) NOT NULL,
    order_date DAFAULT CURRENT_TIMESTAMP);